name: semgrep check

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

permissions:
  contents: read
  security-events: write

jobs:
  semgrep:                      
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep@sha256:93963d9295a366f59e4850127b1550400ee7b388f04fe144e4a1f6325d96e01b

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1 
      
      - name: Semgrep scan
        run: semgrep scan --config p/python --error --sarif --output semgrep.sarif

      - name: Upload SARIF
        if: always()
        uses: github/codeql-action/upload-sarif@24c54180a607b1449ed407dd24f251e4e9147c8d  # v4.38.3
        with:
          sarif_file: semgrep.sarif
